### ISSUE TITLE
Can you share the bash script used to reproduce your results?

### ISSUE THREAD

**Issue by mxzel** [pxiangwu/TopoFilter#1]

**Comment by pxiangwu** [comment]
Hi, for CIFAR10/100, the bash is like this:
```
python train.py --every 5 --start_clean 30 --k_cc 4 --k_outlier 32 --seed 77 --type uniform --noise 0.4 --patience 65 --gpus 0 --dataset cifar10 --zeta 0.5
```
When the noise level is extremely high (>=80%), the assumptions of our method may not hold in practice, and we may need to tune the parameters. In the experiments, I used the following parameters when the noise level is high. (1) for CIFAR10, I used a large `k_cc=10`, `k_outlier=16` and `start_clean=80`. (2) for CIFAR100, I used `k_cc=16`, `k_outlier=64` and `start_clean=80`. 

For point cloud data, the bash is like this:
(1) When the noise level is 40%:
```
python train.py --gpus 2 --every 5 --start_clean 25 --k_outlier 8 --k_cc 25 --noise 0.4 --type uniform --patience 60 --seed 77 --dataset pc --net pc --milestone 35 --zeta 2
```
(2) When the noise level is 80%:
```
python train.py --gpus 2 --every 5 --start_clean 10 --k_outlier 30 --k_cc 100 --noise 0.8 --type uniform --patience 60 --seed 77 --dataset pc --net pc --milestone 35 --zeta 2
```

Hope this helps.

**Comment by mxzel** [comment]
Got it. Thanks!
