### ISSUE TITLE
cannot pip package named PythonGraphPers_withCompInfo

### ISSUE THREAD

**Issue by rh211** [pxiangwu/TopoFilter#2]
hi，sorry to bother you.
i cannot pip the package named PythonGraphPers_withCompInfo in knn_untils.py.
where to download this package？
thanks for answering my question.

**Comment by pxiangwu** [comment]
Hi, PythonGraphPers_withCompInfo is not a package. It is a pybind c++ library. All you need to do is compile the c++ code by following the readme instruction.
