### ISSUE TITLE
tabular data/ noisy instances 

### ISSUE THREAD

**Issue by nazaretl** [pxiangwu/TopoFilter#4]
Hi,
thanks for sharing your implementation. I have two questions about it:

1.	Does it also work on tabular data?
2.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set)?

Thanks!

**Comment by pxiangwu** [comment]
Hello,

For your questions:

> 1. Does it also work on tabular data?

It can also work on tabular data, as long as you have some "models" to extract the features from tabular data (just like we extract features from images).

> 2. Is the code tailored to the datasets used in the paper or can one apply it to any data?

Currently this code only applies to image data. But if you want to apply it to other types of data, all you need to do is replace the `resnet` backbone with other appropriate types of models to extract the data features.

> 3. Is it possible to identify the noisy instances (return the noisy IDs or the clean set)?

Yes. In each data cleansing step, we identify the clean data, from which we can naturally identify the noisy data (i.e., noisy data := Total data - Clean data).

**Comment by nazaretl** [comment]
thank you very much!
